### ISSUE TITLE
Database license?

### ISSUE THREAD

**Issue by EtherTyper** [cheer4ftc/ftc-data#1]
Can we use this data freely and redistribute? I would like to use it on https://ftc-root.herokuapp.com/.

If you're not sure what a good open source database license is, I would suggest the [ODbL](http://opendatacommons.org/licenses/odbl/1-0/).

**Comment by cheer4ftc** [comment]
The data has been gathered from the Event Results spreadsheet released on the FTC website and other FIRST affiliate partner data releases, similar to what is already available on ftcroot.com and ftcstats.org. I make no claims of ownership on the data itself.  As far as I am concerned, you are free to use it as you see fit including but not limited to the ftc-root.herokuapp.com site. I make no guarantees about accuracy, suitability, etc. Not being a lawyer, I am reluctant to agree to any specific license without fully understanding all of the terms, but I agree to make no claims against anyone who uses the data for any purpose. If you have additional event results (e.g., for the California events already posted on ftcroot.com), I would appreciate receiving them so they can also be included in the ftc-data github repo.
