### ISSUE TITLE
Question about data source

### ISSUE THREAD

**Issue by akash329d** [cheer4ftc/ftc-data#6]
Hi,
I noticed that you added detailed match results for Minnesota data with results from Auto/Teleop and penalties separately. I was wondering where you got the detailed results as I can only find final match results on the affiliate partner page?
Thanks!

**Comment by cheer4ftc** [comment]
FIRST recently released the MN details in the latest update to the event results spreadsheet available on this page: http://www.firstinspires.org/resource-library/ftc/game-and-season-info
