### ISSUE TITLE
calaa1a2ilt missing

### ISSUE THREAD

**Issue by sungjuchoi** [cheer4ftc/ftc-data#7]
CA LA A1A2 ILT is missing from the data in CALA. Here is the link to share FLABOB_A_ILT.zip https://drive.google.com/open?id=0Byy2CcZ9qX77S2txM3VFMjAwaTQ

Nice work.
Thanks again.

**Comment by cheer4ftc** [comment]
Added. Thanks!  Don't know how that one slipped by unnoticed.  :)
