### ISSUE TITLE
MN State Data

### ISSUE THREAD

**Issue by heightdifferential** [cheer4ftc/ftc-data#8]
Hi! 
We just saw that the MN state data was posted on High Tech Kids website. We thought you might like to know! (http://www.hightechkids.org/mn-ftc-state-championship)
Thanks, this data is really helpful!

**Comment by cheer4ftc** [comment]
Thanks!  I posted the mn-cmp event data. Expect to see it on ftcstats and ftcroot within a few days.  Too bad MN only posts match results and not match details...  :(
